```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-eks

managedNodeGroups:
  - name: demoeks-nodes
    instanceType: t3.micro
    desiredCapacity: 4
    iam:
      withAddonPolicies:
        albIngress: true
    ssh:
      publicKeyPath: /path/to/public/key

kubernetesVersion: "1.21"

```
